app = "speaking-bot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  PORT = "8080"
